on: 
  workflow_dispatch:
    inputs:
      comment:
        description: 'This is a text messege from github actions!'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: snow-actions/nostr@v1.2.0
      with:
        relays: |
          ${{ vars.NOSTR_RELAY_1 }}
        private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
        content: |
          ${{ github.event.inputs.comment }}
